server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bms
    username: root
    password: 123456
  data:
    redis:
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.whut.sept.zuul.pojo
  configuration:
    map-underscore-to-camel-case: true

